### ISSUE TITLE
Bazelifying All Components 🥦  💚

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1465]
# Roadmap to build all components with Bazel

The goal is that every component has a `:compile`, `:test` and `:stylelint` target. As reference use the components that are already built with Bazel.

- [x] alert
- [x] autocomplete
- [x] bar-indicator
- [x] breadcrumbs
- [x] button
- [x] button-group
- [x] card
- [x] chart
- [x] checkbox @thomaspink #1470                      
- [x] confirmation-dialog
- [x] **consumption** @SkaillZ #1496 
- [x] container-breakpoint-observer
- [x] **context-dialog** @SkaillZ #1589
- [x] copy-to-clipboard  @SkaillZ #1604        
- [x] core 
- [x] **drawer** #1546
- [x] **empty-state** @SkaillZ #1590    
- [x] **event-chart**                  
- [x] **expandable-panel**  @SkaillZ #1595
- [x] **expandable-section** @lukasholzer #1623
- [x] expandable-text
- [x] experimental/**combobox**
- [x] experimental/drawer-table
- [x] **experimental/quick-filter** @SkaillZ #1600
- [x] filter-field
- [x] form-field
- [x] formatters
- [x] highlight
- [x] icon
- [x] indicator  @SkaillZ #1606              
- [x] info-group  @SkaillZ #1607               
- [x] inline-editor @SkaillZ #1608
- [x] input
- [x] key-value-list          
- [x] legend  @SkaillZ #1602
- [x] loading-distractor           
- [x] menu @SkaillZ #1609
- [x] micro-chart @SkaillZ #1610
- [x] overlay          
- [x] **pagination** @SkaillZ #1601
- [x] progress-bar @heartdisease #1483
- [x] progress-circle #1693 
- [x] **radial-chart** #1719  
- [x] radio
- [ ] schematics
- [x] secondary-nav
- [x] select @SkaillZ #1471
- [x] show-more @NinaKammerlander 
- [x] slider @bardosmisi #1476 
- [x] **stacked-series-chart** #1695 
- [x] stepper #1696 
- [x] **sunburst-chart** #1697 
- [x] switch @lukasholzer #1459
- [x] **table** 
- [x] tabs #1334 
- [x] tag #1325 
- [x] theming #1323 
- [x] tile #1320 
- [x] timeline-chart #1699 
- [x] toast #1700 
- [x] toggle-button-group #1701 
- [x] top-bar-navigation #1702 
- [x] **tree-table** #1721 

@dynatrace-oss/barista everybody should grab a component assign itself by writing his name next to the component and start bazelifying.

Keep in mind that you need to bazelify all its dependencies (other libraries first) To check the dependencies you can run `npm run dep-graph`. Then click on the blue button of a library and it will only display its dependents.

For example:
![image](https://user-images.githubusercontent.com/11156362/89783944-15d1f200-db18-11ea-96cb-b1ac2e7032cb.png)
