### ISSUE TITLE
Barista: Integrate examples into barista

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#45]
- [x] Generate metadata for page-builder
- [x] Inject sources into live-example tags in page-builder
- [x] Instantiate and run demo in live-example
- [x] Display sources in live-example
- [x] Style and build basic live-example
- [x] Add scss, issue #285  PR: #484 
- [x] Add copy to clipboard (for ts, html and scss) PR: #366 
- [x] Add show-more functionality for long examples PR: #366
- [x] Add syntax highlighting for ts, html and scss PR: #366
