### ISSUE TITLE
Ng upgrade 7.0.0

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#909]
# Feature Request

Provide an ng-upgrade schematic for version 7.0.0. 
Similar to the upgrade schematic we had for 6.0.0. 
* Rename inputs in templates and ts files (aria-label-close -> ariaLabelClose)
* Install & update peerDependencies (lodash-es, highcharts)

## TODO

- [x] Rename aria labels in html files automatically
    - [x] For example: Consumer is doing [timestamp.html](https://github.com/dynatrace-oss/barista/blob/master/apps/components-e2e/src/components/chart/selection-area/timestamp/timestamp.html#L3) 
- [ ] ~Refactor element from dtBreadcrumbsItem to anchor (**occurrences in cluster**: none)~
- [x] Refactor `dt-cta-*` elements to `dt-empty-state` (occurrences: 1)
- [ ] ~FiltlerField use `currentTags` instead of `tags` (occurrences: none)~
- [ ] ~Refactor dtTime to dtDuration formatter (occurrences: none)~
- [x] Refactor `dt-empty-state-item-img` selector to `dt-empty-state` (occurrences: 116)
- [x] Refactor `dt-table-empty-state-message` selector to `dt-empty-state` (occurrences: 10)
- [x] Refactor `dt-table-empty-state-title` selector to `dt-empty-state` (occurrences: 6)
- [x] Refactor `dt-table-empty-state` selector to `dt-empty-state` (occurrences: 28)
- [x] Refactor `dtTableEmptyState` anchor to `dt-empty-state` (occurrences: 3)

**Comment by lukasholzer** [comment]
We need to update the `ng-add` as well for the latest versions.
